"use strict";

const res1 = "8" + 2;
console.log("Результат:", res1);
console.log("Тип результата:", typeof res1);
const res2 =  "8" - 2;
console.log("Результат:", res2);
console.log("Тип результата:", typeof res2);
const res3 = Number("8") + 2;
console.log("Результат:", res3);
console.log("Тип результата:", typeof res3);
const res4 = "12" > "3";
console.log("Результат:", res4);
console.log("Тип результата:", typeof res4);
const res5 = 12 === "12";
console.log("Результат:", res5);
console.log("Тип результата:", typeof res5);
const res6 = Number("");
console.log("Результат:", res6);
console.log("Тип результата:", typeof res6);
const res7 = Number("text");
console.log("Результат:", res7);
console.log("Тип результата:", typeof res7);
const res8 = Boolean("false");
console.log("Результат:", res8);
console.log("Тип результата:", typeof res8);
const res9 = typeof null;
console.log("Результат:", res9);
console.log("Тип результата:", typeof res9);
const res10 = typeof NaN;
console.log("Результат:", res10);
console.log("Тип результата:", typeof res10);